// Clocked-torque G-SLIP pronk controller.
//
// Runs the SLIP-RF running template of Lu & Lin 2024 on the Corgi, with all
// four legs in phase so they reduce to a single virtual leg.
//
// The template itself is generated by the LegWheel package
// (examples/gslip/export_pronk_csv.py) and loaded here as a reference table,
// which keeps the model in one place rather than duplicating the fixed-point
// solve in C++. Each row is one 1 ms control tick and carries the reference
// pose plus a stance flag.
//
// Two impedance regimes, switched by that flag:
//   STANCE  leg-frame stiffness -- a stiff radial spring along the leg (the
//           virtual k_t the rigid linkage cannot provide) and a soft
//           tangential term, so the leg is compliant along its axis while
//           still tracking the swing.
//   FLIGHT  body-frame position tracking; the leg is unloaded and only has to
//           be repositioned for the next touchdown.
//
// The clocked torque is not optional here. A fine sweep of the model
// (LegWheel examples/gslip/corgi_stability_sweep.py) found no self-stable
// running gait for this geometry at any landing angle, stiffness or speed:
// |dP/dalpha| bottoms out around 1.15. The instability is mild -- an error
// grows ~15% per stride, doubling in about 5 strides -- so this loop has
// ample authority, but without it the gait does not persist.

#include <chrono>
#include <fstream>
#include <memory>
#include <sstream>
#include <string>
#include <thread>
#include <vector>

#include <Eigen/Dense>

#include "ament_index_cpp/get_package_share_directory.hpp"
#include "rclcpp/rclcpp.hpp"
#include "corgi_msgs/msg/impedance_cmd_stamped.hpp"
#include "corgi_msgs/msg/motor_state_stamped.hpp"
#include "corgi_msgs/msg/trigger_stamped.hpp"
#include "corgi_msgs/msg/imu_stamped.hpp"

struct TemplateRow {
    double t;
    double theta;
    double beta;
    double gamma;
    bool in_stance;
};

class GslipPronkNode : public rclcpp::Node {
public:
    GslipPronkNode();
    void run();

private:
    void trigger_cb(const corgi_msgs::msg::TriggerStamped::SharedPtr msg);
    void motor_state_cb(const corgi_msgs::msg::MotorStateStamped::SharedPtr msg);
    void imu_cb(const corgi_msgs::msg::ImuStamped::SharedPtr msg);

    bool load_template(const std::string& path);
    void apply_row(const TemplateRow& row);
    void execute_standup_phase();
    void execute_running_phase();

    rclcpp::Publisher<corgi_msgs::msg::ImpedanceCmdStamped>::SharedPtr imp_cmd_pub_;
    rclcpp::Subscription<corgi_msgs::msg::TriggerStamped>::SharedPtr trigger_sub_;
    rclcpp::Subscription<corgi_msgs::msg::MotorStateStamped>::SharedPtr motor_state_sub_;
    rclcpp::Subscription<corgi_msgs::msg::ImuStamped>::SharedPtr imu_sub_;

    corgi_msgs::msg::ImpedanceCmdStamped imp_cmd_;
    corgi_msgs::msg::MotorStateStamped motor_state_;
    corgi_msgs::msg::ImuStamped imu_;

    std::vector<corgi_msgs::msg::ImpedanceCmd*> imp_cmd_modules_;
    std::vector<TemplateRow> template_;

    bool trigger_;
    bool sim_;

    // Stance: the virtual leg spring, split across four legs in a pronk.
    // k_radial = k_rel * m * g / l0 / 4 with k_rel = 18, at the nominal stance
    // theta = 100 deg (l0 = 0.1481 m, hip 0.2931 m) -> 8941 N/m per leg.
    //
    //   m = 30.00 kg  measured on scales
    //   m = 30.84 kg  summed from CorgiRobotABAD.proto -- agrees to 2.8%
    //
    // so one value covers both. Peak motor torque ~14 N.m, 41% of the limit.
    //
    // The nominal stance is deliberately NOT the paper's r~ = 0.6303 optimum,
    // which for this robot is a 0.230 m crouch. Standing at 0.293 m instead
    // costs only a slope penalty (1.154 -> 1.232) and buys a 26% lower peak
    // ground reaction, 41% rather than 53% torque, and a 43% softer spring --
    // the last mattering most, since a softer virtual spring is much less
    // corrupted by the 0.36-0.68 N.m joint friction. See LegWheel
    // examples/gslip/stance_height_tradeoff.py.
    //
    // Only the stiffness would change with mass anyway: since
    // k = k_rel*m*g/l0, the ratio k/m is mass-independent and the stance EOM
    // divides through by m, so the template, the fixed point (beta 74.75 deg,
    // alpha 23.75 deg) and the GRF in body weights are all identical.
    //
    // k_lateral holds the ABAD axis. It must NOT be zero: with leg_frame the
    // lateral axis is the ABAD direction, so K_joint = J^T K J would give a
    // near-zero kp_h and the hip roll would go floppy.
    //
    // Sizing it from the 0.0917 m ABAD-to-wheel-plane offset was wrong. At
    // k_lateral = 30000 the measured kp_h was 972 N.m/rad, not the ~250
    // intended, so the effective moment arm in the Jacobian is nearer 0.18 m.
    // That over-stiff ABAD fed large off-diagonal coupling torques into the
    // leg motors: applied torque peaked at 33-35 N.m against the 35 N.m limit
    // while the model predicted 14 N.m, and the leg could not reach its
    // commanded extension because it was torque-limited, not
    // stiffness-limited. 7500 N/m gives roughly the 250 N.m/rad originally
    // wanted, which held gamma to about 1 degree.
    // b_radial defaults to ZERO, and that is deliberate. The G-SLIP model is
    // conservative: the spring returns everything it stores, so any radial
    // damping is a deviation from the model rather than a refinement of it.
    // The original 72 came from a rule of thumb (0.008*k), not the physics.
    //
    // An energy audit over the hop showed why it mattered. At b_radial = 72
    // the motors did 105 W of positive work and took 99.6 W straight back out,
    // netting only 5.5 W: energy was being absorbed during extension as fast
    // as the spring released it, so the body decelerated while still in
    // contact and never lifted off. At b_radial = 0 the braking work fell to
    // 77.6 W, net rose to 27.9 W, peak vertical velocity went 1.109 -> 1.503
    // m/s and the flight phase went 4.0% -> 31.9%.
    double k_radial_;
    double k_tangential_;
    double k_lateral_;
    double b_radial_;
    double b_tangential_;
    double b_lateral_;

    // Flight: body-frame position tracking on an unloaded leg.
    //
    // These have to be STIFF, not gentle. theta = 100 deg is the touchdown
    // pose and is reached at the END of flight, so the leg must retract and
    // re-extend through the full 15.6 deg sweep in the 127 ms flight window.
    // At k_flight = 2000 it managed only 50% of the commanded excursion and
    // touched down 11 deg short, which left the spring far less compression
    // than the template assumes, weakened push-off, and killed the flight
    // phase entirely. The leg is unloaded here, so stiff tracking is cheap.
    double k_flight_;
    double b_flight_;

    int standup_ticks_;

    // --- Body attitude correction through the ABAD joints -------------------
    //
    // The clocked-torque template shapes where the LEGS go; it contains no
    // body-level feedback at all. With |dP/dalpha| ~ 1.23 the gait is
    // unstable, so a symmetric start develops an asymmetry that grows: the
    // measured pronk stayed level in roll and pitch (< 1.5 deg) but yawed
    // 14.8 deg in 10 s, driven by the right legs carrying ~50% more contact
    // time than the left. Nothing in the controller opposed it.
    //
    // The paper's TWIX gets away without this because an alternating tripod
    // is inherently yaw-symmetric. A four-legged pronk is not.
    //
    // gamma tilts the leg laterally, moving the contact point sideways, so
    // differential gamma generates the lateral ground reaction needed for
    // roll and yaw moments:
    //   roll : left legs one way, right legs the other   (A,D vs B,C)
    //   yaw  : front legs one way, rear legs the other   (A,B vs C,D)
    //
    // Gain SIGNS are not obvious from the geometry -- if a correction makes
    // things worse, negate the gain. They are parameters for that reason.
    void update_attitude(double& roll, double& pitch, double& yaw) const;
    double gamma_correction(int leg_index) const;

    // Rest-length leg extension, taken from the template's maximum theta
    // (its touchdown pose, where the spring is uncompressed).
    double theta_rest_{0.0};
    bool spring_rest_reference_;

    double roll_{0.0}, pitch_{0.0}, yaw_{0.0};
    double yaw_ref_{0.0};
    bool yaw_ref_set_{false};

    double k_roll_;
    double d_roll_;
    double k_yaw_;
    double d_yaw_;
    double gamma_limit_;   // rad, clamp on the correction

    // Ticks to hold the stance after the trigger, before the stride starts.
    // In experiment mode the same /trigger that starts this gait also deletes
    // SUPPORT_BOX, so the robot is settling onto its legs at that instant.
    // Striding through the settle would corrupt the first touchdown.
    //
    // Raised 1000 -> 2500 on 2026-08-08. 1 s was marginal: per-stride hop data
    // across eight ramp runs shows the opening strides frequently below par and
    // then recovering, and in the worst case the robot took FIVE strides
    // (~1.34 s) to start hopping at all -- 0, 0, 0, 0, 0, 3.4, 15.0, 56.2% --
    // which failed the run's validity gate outright. Even a healthy run showed
    // a one-to-two stride transient (21.4, 55.1, then 70s). The cost is ~1.5 s
    // of extra sim time per run, against a 9.57 s pass; the benefit is fewer
    // discarded runs, and the hop segment IS the gate.
    int settle_ticks_;

    // Phase 5 step 1: hold the standing pose with the STANCE (leg-frame)
    // impedance rather than the flight gains, so the virtual spring can be
    // probed by pushing the body before anything hops.
    bool hold_stance_;
};

GslipPronkNode::GslipPronkNode()
    : Node("gslip_pronk"),
      trigger_(false),
      sim_(false),
      k_radial_(8941.0),
      k_tangential_(900.0),
      k_lateral_(7500.0),
      b_radial_(0.0),
      b_tangential_(30.0),
      b_lateral_(60.0),
      k_flight_(12000.0),
      b_flight_(150.0),
      standup_ticks_(2000),
      // Gentle. At k_roll 0.6 / k_yaw 0.4 with a 12 deg clamp the correction
      // saturated -- measured gamma reached 15-17 deg -- and while it did halve
      // the yaw drift and even out the contact balance, tilting the legs that
      // far cost the vertical push: flight fell from 34% to 8.9% and the leg
      // phase correlation from 0.92-0.98 to 0.70-0.91. The authority has to
      // stay small enough not to disturb the hop it is stabilising.
      k_roll_(0.25),
      d_roll_(0.03),
      k_yaw_(0.15),
      d_yaw_(0.02),
      gamma_limit_(5.0 / 180.0 * M_PI),
      // Default OFF. The reasoning is sound for the model -- l0 is the rest
      // length and l(t) is an output -- but in the robot it flipped the
      // machine: measured compression already reaches 71-75 deg, so
      // referencing from 100 deg rest gives 29 deg of compression, about
      // 492 N per leg or 6.7 body weights against the model's 3.64, and the
      // resulting push threw it over (145 deg tilt, legs folded past their
      // 17 deg limit).
      //
      // The discrepancy is not in this reference choice. It is that the robot
      // is nowhere near the fixed point the template was solved for: that
      // fixed point assumes 2.035 m/s of forward travel, and the robot is
      // essentially hopping in place. Touchdown velocity, and therefore
      // compression, are simply not the model's.
      spring_rest_reference_(false),
      settle_ticks_(2500),
      hold_stance_(false)
{
    RCLCPP_INFO(this->get_logger(), "G-SLIP pronk controller starting");

    this->get_parameter_or("use_sim_time", sim_, false);

    const std::string default_template =
        ament_index_cpp::get_package_share_directory("corgi_force_control")
        + "/config/gslip_pronk_template.csv";
    std::string template_path =
        this->declare_parameter<std::string>("template_path", default_template);
    // Launch files pass an empty string to mean "use the installed default"
    // rather than having to repeat the share-directory lookup.
    if (template_path.empty()) template_path = default_template;

    k_radial_ = this->declare_parameter<double>("k_radial", k_radial_);
    k_tangential_ = this->declare_parameter<double>("k_tangential", k_tangential_);
    k_lateral_ = this->declare_parameter<double>("k_lateral", k_lateral_);
    b_radial_ = this->declare_parameter<double>("b_radial", b_radial_);
    b_tangential_ = this->declare_parameter<double>("b_tangential", b_tangential_);
    b_lateral_ = this->declare_parameter<double>("b_lateral", b_lateral_);
    k_flight_ = this->declare_parameter<double>("k_flight", k_flight_);
    b_flight_ = this->declare_parameter<double>("b_flight", b_flight_);
    standup_ticks_ = this->declare_parameter<int>("standup_ticks", standup_ticks_);
    hold_stance_ = this->declare_parameter<bool>("hold_stance", hold_stance_);
    settle_ticks_ = this->declare_parameter<int>("settle_ticks", settle_ticks_);
    k_roll_ = this->declare_parameter<double>("k_roll", k_roll_);
    d_roll_ = this->declare_parameter<double>("d_roll", d_roll_);
    k_yaw_ = this->declare_parameter<double>("k_yaw", k_yaw_);
    d_yaw_ = this->declare_parameter<double>("d_yaw", d_yaw_);
    gamma_limit_ = this->declare_parameter<double>("gamma_limit", gamma_limit_);
    spring_rest_reference_ =
        this->declare_parameter<bool>("spring_rest_reference", spring_rest_reference_);

    if (sim_) {
        RCLCPP_INFO(this->get_logger(), "Waiting for Webots clock...");
        while (rclcpp::ok()) {
            rclcpp::spin_some(this->get_node_base_interface());
            if (this->now().seconds() > 0.0) {
                RCLCPP_INFO(this->get_logger(), "Clock synced! Sim Time: %.2f",
                            this->now().seconds());
                break;
            }
            rclcpp::sleep_for(std::chrono::milliseconds(100));
        }
    } else {
        RCLCPP_INFO(this->get_logger(), "Real hardware mode: using system wall clock.");
    }

    imp_cmd_pub_ = this->create_publisher<corgi_msgs::msg::ImpedanceCmdStamped>(
        "impedance/command", 1000);
    trigger_sub_ = this->create_subscription<corgi_msgs::msg::TriggerStamped>(
        "trigger", 1000,
        std::bind(&GslipPronkNode::trigger_cb, this, std::placeholders::_1));
    motor_state_sub_ = this->create_subscription<corgi_msgs::msg::MotorStateStamped>(
        "motor/state", 1000,
        std::bind(&GslipPronkNode::motor_state_cb, this, std::placeholders::_1));
    imu_sub_ = this->create_subscription<corgi_msgs::msg::ImuStamped>(
        "imu", 1000,
        std::bind(&GslipPronkNode::imu_cb, this, std::placeholders::_1));

    imp_cmd_modules_ = {
        &imp_cmd_.module_a,
        &imp_cmd_.module_b,
        &imp_cmd_.module_c,
        &imp_cmd_.module_d
    };

    if (!load_template(template_path)) {
        RCLCPP_FATAL(this->get_logger(),
                     "Could not load the stride template from '%s'. Generate it with "
                     "LegWheel: uv run python examples/gslip/export_pronk_csv.py",
                     template_path.c_str());
        throw std::runtime_error("missing stride template");
    }

    // The spring is uncompressed at touchdown, so the template's maximum
    // theta is the rest extension.
    theta_rest_ = template_.front().theta;
    for (const auto& row : template_) theta_rest_ = std::max(theta_rest_, row.theta);

    RCLCPP_INFO(this->get_logger(),
                "Loaded %zu template rows (%.4f s stride), k_radial=%.0f N/m per leg",
                template_.size(), template_.back().t, k_radial_);
    RCLCPP_INFO(this->get_logger(),
                "Radial reference: %s (rest theta %.2f deg)",
                spring_rest_reference_ ? "SPRING REST (constant)"
                                       : "template trajectory",
                theta_rest_ * 180.0 / M_PI);
}

void GslipPronkNode::trigger_cb(const corgi_msgs::msg::TriggerStamped::SharedPtr msg) {
    trigger_ = msg->enable;
}

void GslipPronkNode::motor_state_cb(const corgi_msgs::msg::MotorStateStamped::SharedPtr msg) {
    motor_state_ = *msg;
}

void GslipPronkNode::imu_cb(const corgi_msgs::msg::ImuStamped::SharedPtr msg) {
    imu_ = *msg;
}

bool GslipPronkNode::load_template(const std::string& path) {
    std::ifstream file(path);
    if (!file.is_open()) return false;

    std::string line;
    if (!std::getline(file, line)) return false;  // header

    template_.clear();
    while (std::getline(file, line)) {
        if (line.empty()) continue;
        std::stringstream ss(line);
        std::string cell;
        TemplateRow row{};
        std::vector<double> values;
        while (std::getline(ss, cell, ',')) {
            values.push_back(std::stod(cell));
        }
        if (values.size() < 5) return false;
        row.t = values[0];
        row.theta = values[1];
        row.beta = values[2];
        row.gamma = values[3];
        row.in_stance = values[4] > 0.5;
        template_.push_back(row);
    }
    // The final row is the wrap-around of the first; dropping it keeps the
    // cycle from stalling for one tick at every stride boundary.
    if (template_.size() > 1) template_.pop_back();
    return template_.size() > 1;
}

void GslipPronkNode::update_attitude(double& roll, double& pitch, double& yaw) const {
    const double x = imu_.orientation.x, y = imu_.orientation.y;
    const double z = imu_.orientation.z, w = imu_.orientation.w;
    roll = std::atan2(2.0 * (w * x + y * z), 1.0 - 2.0 * (x * x + y * y));
    pitch = std::asin(std::max(-1.0, std::min(1.0, 2.0 * (w * y - z * x))));
    yaw = std::atan2(2.0 * (w * z + x * y), 1.0 - 2.0 * (y * y + z * z));
}

double GslipPronkNode::gamma_correction(int leg_index) const {
    if (!yaw_ref_set_) return 0.0;

    // Module order is A=FL, B=FR, C=RR, D=RL.
    static const double roll_sign[4] = {+1.0, -1.0, -1.0, +1.0};  // left vs right
    static const double yaw_sign[4] = {+1.0, +1.0, -1.0, -1.0};   // front vs rear

    double yaw_err = yaw_ - yaw_ref_;
    while (yaw_err > M_PI) yaw_err -= 2.0 * M_PI;
    while (yaw_err < -M_PI) yaw_err += 2.0 * M_PI;

    const double wx = imu_.angular_velocity.x;  // roll rate
    const double wz = imu_.angular_velocity.z;  // yaw rate

    const double correction =
        roll_sign[leg_index] * (k_roll_ * roll_ + d_roll_ * wx) +
        yaw_sign[leg_index] * (k_yaw_ * yaw_err + d_yaw_ * wz);

    return std::max(-gamma_limit_, std::min(gamma_limit_, correction));
}

void GslipPronkNode::apply_row(const TemplateRow& row) {
    update_attitude(roll_, pitch_, yaw_);

    // The radial reference is the spring's REST length, not the template's
    // compressed trajectory.
    //
    // In SLIP-RF the rest length l0 is constant and l(t) is what the dynamics
    // produce under load -- an output, not a setpoint. Feeding l(t) to an
    // impedance controller as its rest position makes the leg compress by
    // F/k on top of a trajectory that already contains the compression,
    // double-counting it. Measured: commanded theta bottomed at 84.4 deg
    // while the leg reached 71-75 deg, 10-13 deg deeper on every damping
    // setting tried.
    //
    // Holding theta at the rest value instead reproduces the model: the leg
    // compresses to 84.4 deg under load, which at 8941 N/m is 262 N per leg,
    // 1048 N total, 3.56 body weights -- against the 3.64 the fixed point
    // predicts.
    //
    // beta still follows the template: that is the clocked-torque part, the
    // leg angle the controller genuinely has to drive.
    const double theta_ref = spring_rest_reference_ ? theta_rest_ : row.theta;

    for (size_t i = 0; i < imp_cmd_modules_.size(); i++) {
        auto* cmd = imp_cmd_modules_[i];
        cmd->theta = theta_ref;
        cmd->beta = row.beta;
        cmd->gamma = row.gamma + gamma_correction(static_cast<int>(i));

        // No force feedback yet: with fx/fy/fz and the inertia terms at zero,
        // force_control degenerates to a pure (K, B) impedance and needs no
        // contact-force estimate.
        cmd->fx = 0.0; cmd->fy = 0.0; cmd->fz = 0.0;
        cmd->mx = 0.0; cmd->my = 0.0; cmd->mz = 0.0;

        if (row.in_stance) {
            cmd->leg_frame = true;
            cmd->kx = k_radial_;      // along the leg: the virtual spring
            cmd->ky = k_lateral_;
            cmd->kz = k_tangential_;  // perpendicular, in the sagittal plane
            cmd->bx = b_radial_;
            cmd->by = b_lateral_;
            cmd->bz = b_tangential_;
        } else {
            cmd->leg_frame = false;
            cmd->kx = k_flight_;
            cmd->ky = k_flight_;
            cmd->kz = k_flight_;
            cmd->bx = b_flight_;
            cmd->by = b_flight_;
            cmd->bz = b_flight_;
        }
    }
    // NO per-side beta mirroring. corgi_driver already applies dir_beta
    // (+1, -1, -1, +1 for A..D from motor_config.yaml) to both the command
    // and the reported state, so the left/right mounting mirror is handled
    // there. Sending the same beta to all four legs is what makes them swing
    // the same physical direction -- which is what a pronk requires.
    //
    // exp_sim_stay does negate beta for B and C, but that is to SPLAY the
    // legs into a wide static standing stance. Applying it here double-flipped
    // the right side so it moved opposite to the left, producing a left/right
    // alternating pattern instead of a pronk: legs A and D swung +/-20 deg
    // while B and C managed only -14..+7 deg.
}

void GslipPronkNode::execute_standup_phase() {
    // Ramp from wherever the robot actually is, not from a hardcoded folded
    // pose. If a CSV has already stood the robot up (theta ~ 120 deg),
    // starting the ramp at 17 deg commands an immediate collapse.
    //
    // A single spin_some() is NOT enough: the subscription has not yet
    // discovered the publisher at construction time, so motor_state_ is still
    // zero-initialised and the fallback fires even though the robot is
    // standing. Wait for a real sample. Wall-clock sleep, deliberately -- this
    // must work before the sim clock is known to be running.
    const int kMaxWaitMs = 5000;
    int waited_ms = 0;
    while (rclcpp::ok() && motor_state_.module_a.theta == 0.0 && waited_ms < kMaxWaitMs) {
        rclcpp::spin_some(this->get_node_base_interface());
        std::this_thread::sleep_for(std::chrono::milliseconds(10));
        waited_ms += 10;
    }

    double theta_start = motor_state_.module_a.theta;
    double beta_start = motor_state_.module_a.beta;
    if (theta_start == 0.0) {
        theta_start = 17.0 / 180.0 * M_PI;
        beta_start = 0.0;
        RCLCPP_ERROR(this->get_logger(),
                     "No motor/state after %d ms. Assuming the folded pose, which will "
                     "COLLAPSE a standing robot. Check that the simulator is running.",
                     kMaxWaitMs);
    } else {
        RCLCPP_INFO(this->get_logger(), "Got motor/state after %d ms", waited_ms);
    }

    const TemplateRow& first = template_.front();
    RCLCPP_INFO(this->get_logger(),
                "Ramping from measured theta=%.1f deg to template theta=%.1f deg",
                theta_start * 180.0 / M_PI, first.theta * 180.0 / M_PI);

    rclcpp::Duration period(0, 1000000);  // 1 ms
    rclcpp::Time next_time = this->now();

    for (int i = 0; i < standup_ticks_ && rclcpp::ok(); i++) {
        rclcpp::spin_some(this->get_node_base_interface());

        const double s = static_cast<double>(i) / standup_ticks_;
        TemplateRow row{};
        row.t = 0.0;
        row.theta = theta_start + s * (first.theta - theta_start);
        row.beta = beta_start + s * (first.beta - beta_start);
        row.gamma = 0.0;
        row.in_stance = false;  // soft gains while posing
        apply_row(row);

        imp_cmd_.header.stamp = this->now();
        imp_cmd_pub_->publish(imp_cmd_);

        next_time = next_time + period;
        rclcpp::sleep_for(std::chrono::nanoseconds(
            std::max<int64_t>(0, (next_time - this->now()).nanoseconds())));
    }
}

void GslipPronkNode::execute_running_phase() {
    rclcpp::Duration period(0, 1000000);  // 1 ms
    rclcpp::Time next_time = this->now();

    // Latch the heading to hold. Taken AFTER the settle, so the block-removal
    // transient is not baked into the reference.
    yaw_ref_set_ = false;

    // Let the robot settle onto its legs before striding. In experiment mode
    // the trigger that got us here also removed the support box.
    if (settle_ticks_ > 0) {
        RCLCPP_INFO(this->get_logger(), "Settling for %d ms before the first stride",
                    settle_ticks_);
        TemplateRow settle = template_.front();
        settle.in_stance = true;
        for (int i = 0; i < settle_ticks_ && rclcpp::ok() && trigger_; i++) {
            rclcpp::spin_some(this->get_node_base_interface());
            apply_row(settle);
            imp_cmd_.header.stamp = this->now();
            imp_cmd_pub_->publish(imp_cmd_);
            next_time = next_time + period;
            rclcpp::sleep_for(std::chrono::nanoseconds(
                std::max<int64_t>(0, (next_time - this->now()).nanoseconds())));
        }
    }

    update_attitude(roll_, pitch_, yaw_);
    yaw_ref_ = yaw_;
    yaw_ref_set_ = true;
    RCLCPP_INFO(this->get_logger(),
                "Running the G-SLIP pronk template. Holding heading %.1f deg "
                "(k_roll=%.2f k_yaw=%.2f, gamma limit %.1f deg)",
                yaw_ref_ * 180.0 / M_PI, k_roll_, k_yaw_,
                gamma_limit_ * 180.0 / M_PI);
    size_t index = 0;
    size_t stride_count = 0;

    while (rclcpp::ok() && trigger_) {
        rclcpp::spin_some(this->get_node_base_interface());

        apply_row(template_[index]);
        imp_cmd_.header.stamp = this->now();
        imp_cmd_pub_->publish(imp_cmd_);

        index++;
        if (index >= template_.size()) {
            index = 0;
            stride_count++;
            if (stride_count % 10 == 0) {
                RCLCPP_INFO(this->get_logger(), "%zu strides", stride_count);
            }
        }

        next_time = next_time + period;
        rclcpp::sleep_for(std::chrono::nanoseconds(
            std::max<int64_t>(0, (next_time - this->now()).nanoseconds())));
    }

    RCLCPP_INFO(this->get_logger(), "Stopped after %zu strides", stride_count);
}

void GslipPronkNode::run() {
    execute_standup_phase();

    rclcpp::Duration period(0, 1000000);  // 1 ms
    rclcpp::Time next_time = this->now();

    RCLCPP_INFO(this->get_logger(), "Holding pose; waiting for trigger");
    while (rclcpp::ok()) {
        rclcpp::spin_some(this->get_node_base_interface());

        if (trigger_) {
            execute_running_phase();
        } else {
            TemplateRow hold = template_.front();
            hold.in_stance = hold_stance_;
            apply_row(hold);
            imp_cmd_.header.stamp = this->now();
            imp_cmd_pub_->publish(imp_cmd_);
        }

        next_time = next_time + period;
        rclcpp::sleep_for(std::chrono::nanoseconds(
            std::max<int64_t>(0, (next_time - this->now()).nanoseconds())));
    }
}

int main(int argc, char** argv) {
    rclcpp::init(argc, argv);
    auto node = std::make_shared<GslipPronkNode>();
    node->run();
    rclcpp::shutdown();
    return 0;
}
