// Clocked-torque G-SLIP pronk controller.
//
// Runs the SLIP-RF running template of Lu & Lin 2024 on the Corgi, with all
// four legs in phase so they reduce to a single virtual leg.
//
// The template itself is generated by the LegWheel package
// (examples/gslip/export_pronk_csv.py) and loaded here as a reference table,
// which keeps the model in one place rather than duplicating the fixed-point
// solve in C++. Each row is one 1 ms control tick and carries the reference
// pose plus a stance flag.
//
// Two impedance regimes, switched by that flag:
//   STANCE  leg-frame stiffness -- a stiff radial spring along the leg (the
//           virtual k_t the rigid linkage cannot provide) and a soft
//           tangential term, so the leg is compliant along its axis while
//           still tracking the swing.
//   FLIGHT  body-frame position tracking; the leg is unloaded and only has to
//           be repositioned for the next touchdown.
//
// The clocked torque is not optional here. A fine sweep of the model
// (LegWheel examples/gslip/corgi_stability_sweep.py) found no self-stable
// running gait for this geometry at any landing angle, stiffness or speed:
// |dP/dalpha| bottoms out around 1.15. The instability is mild -- an error
// grows ~15% per stride, doubling in about 5 strides -- so this loop has
// ample authority, but without it the gait does not persist.

#include <chrono>
#include <fstream>
#include <memory>
#include <sstream>
#include <string>
#include <thread>
#include <vector>

#include <Eigen/Dense>

#include "ament_index_cpp/get_package_share_directory.hpp"
#include "rclcpp/rclcpp.hpp"
#include "corgi_msgs/msg/impedance_cmd_stamped.hpp"
#include "corgi_msgs/msg/motor_state_stamped.hpp"
#include "corgi_msgs/msg/trigger_stamped.hpp"
#include "corgi_msgs/msg/imu_stamped.hpp"

struct TemplateRow {
    double t;
    double theta;
    double beta;
    double gamma;
    bool in_stance;
};

class GslipPronkNode : public rclcpp::Node {
public:
    GslipPronkNode();
    void run();

private:
    void trigger_cb(const corgi_msgs::msg::TriggerStamped::SharedPtr msg);
    void motor_state_cb(const corgi_msgs::msg::MotorStateStamped::SharedPtr msg);
    void imu_cb(const corgi_msgs::msg::ImuStamped::SharedPtr msg);

    bool load_template(const std::string& path);
    void apply_row(const TemplateRow& row);
    void execute_standup_phase();
    void execute_running_phase();

    rclcpp::Publisher<corgi_msgs::msg::ImpedanceCmdStamped>::SharedPtr imp_cmd_pub_;
    rclcpp::Subscription<corgi_msgs::msg::TriggerStamped>::SharedPtr trigger_sub_;
    rclcpp::Subscription<corgi_msgs::msg::MotorStateStamped>::SharedPtr motor_state_sub_;
    rclcpp::Subscription<corgi_msgs::msg::ImuStamped>::SharedPtr imu_sub_;

    corgi_msgs::msg::ImpedanceCmdStamped imp_cmd_;
    corgi_msgs::msg::MotorStateStamped motor_state_;
    corgi_msgs::msg::ImuStamped imu_;

    std::vector<corgi_msgs::msg::ImpedanceCmd*> imp_cmd_modules_;
    std::vector<TemplateRow> template_;

    bool trigger_;
    bool sim_;

    // Stance: the virtual leg spring, split across four legs in a pronk.
    // k_radial = k_rel * m * g / l0 / 4 with k_rel = 18, at the nominal stance
    // theta = 100 deg (l0 = 0.1481 m, hip 0.2931 m) -> 8941 N/m per leg.
    //
    //   m = 30.00 kg  measured on scales
    //   m = 30.84 kg  summed from CorgiRobotABAD.proto -- agrees to 2.8%
    //
    // so one value covers both. Peak motor torque ~14 N.m, 41% of the limit.
    //
    // The nominal stance is deliberately NOT the paper's r~ = 0.6303 optimum,
    // which for this robot is a 0.230 m crouch. Standing at 0.293 m instead
    // costs only a slope penalty (1.154 -> 1.232) and buys a 26% lower peak
    // ground reaction, 41% rather than 53% torque, and a 43% softer spring --
    // the last mattering most, since a softer virtual spring is much less
    // corrupted by the 0.36-0.68 N.m joint friction. See LegWheel
    // examples/gslip/stance_height_tradeoff.py.
    //
    // Only the stiffness would change with mass anyway: since
    // k = k_rel*m*g/l0, the ratio k/m is mass-independent and the stance EOM
    // divides through by m, so the template, the fixed point (beta 74.75 deg,
    // alpha 23.75 deg) and the GRF in body weights are all identical.
    //
    // k_lateral holds the ABAD axis. It must NOT be zero: with leg_frame the
    // lateral axis is the ABAD direction, so K_joint = J^T K J would give a
    // near-zero kp_h and the hip roll would go floppy. Each leg carries about
    // m*g*0.0917/4 ~ 7 N.m about that axis, so 30 kN/m (~250 N.m/rad through
    // the 0.0917 m moment arm) holds it to under 2 degrees of sag.
    double k_radial_;
    double k_tangential_;
    double k_lateral_;
    double b_radial_;
    double b_tangential_;
    double b_lateral_;

    // Flight: body-frame position tracking on an unloaded leg.
    double k_flight_;
    double b_flight_;

    int standup_ticks_;

    // Ticks to hold the stance after the trigger, before the stride starts.
    // In experiment mode the same /trigger that starts this gait also deletes
    // SUPPORT_BOX, so the robot is settling onto its legs at that instant.
    // Striding through the settle would corrupt the first touchdown.
    int settle_ticks_;

    // Phase 5 step 1: hold the standing pose with the STANCE (leg-frame)
    // impedance rather than the flight gains, so the virtual spring can be
    // probed by pushing the body before anything hops.
    bool hold_stance_;
};

GslipPronkNode::GslipPronkNode()
    : Node("gslip_pronk"),
      trigger_(false),
      sim_(false),
      k_radial_(8941.0),
      k_tangential_(900.0),
      k_lateral_(30000.0),
      b_radial_(72.0),
      b_tangential_(30.0),
      b_lateral_(200.0),
      k_flight_(2000.0),
      b_flight_(100.0),
      standup_ticks_(2000),
      settle_ticks_(1000),
      hold_stance_(false)
{
    RCLCPP_INFO(this->get_logger(), "G-SLIP pronk controller starting");

    this->get_parameter_or("use_sim_time", sim_, false);

    const std::string default_template =
        ament_index_cpp::get_package_share_directory("corgi_force_control")
        + "/config/gslip_pronk_template.csv";
    std::string template_path =
        this->declare_parameter<std::string>("template_path", default_template);
    // Launch files pass an empty string to mean "use the installed default"
    // rather than having to repeat the share-directory lookup.
    if (template_path.empty()) template_path = default_template;

    k_radial_ = this->declare_parameter<double>("k_radial", k_radial_);
    k_tangential_ = this->declare_parameter<double>("k_tangential", k_tangential_);
    k_lateral_ = this->declare_parameter<double>("k_lateral", k_lateral_);
    b_radial_ = this->declare_parameter<double>("b_radial", b_radial_);
    b_tangential_ = this->declare_parameter<double>("b_tangential", b_tangential_);
    b_lateral_ = this->declare_parameter<double>("b_lateral", b_lateral_);
    k_flight_ = this->declare_parameter<double>("k_flight", k_flight_);
    b_flight_ = this->declare_parameter<double>("b_flight", b_flight_);
    standup_ticks_ = this->declare_parameter<int>("standup_ticks", standup_ticks_);
    hold_stance_ = this->declare_parameter<bool>("hold_stance", hold_stance_);
    settle_ticks_ = this->declare_parameter<int>("settle_ticks", settle_ticks_);

    if (sim_) {
        RCLCPP_INFO(this->get_logger(), "Waiting for Webots clock...");
        while (rclcpp::ok()) {
            rclcpp::spin_some(this->get_node_base_interface());
            if (this->now().seconds() > 0.0) {
                RCLCPP_INFO(this->get_logger(), "Clock synced! Sim Time: %.2f",
                            this->now().seconds());
                break;
            }
            rclcpp::sleep_for(std::chrono::milliseconds(100));
        }
    } else {
        RCLCPP_INFO(this->get_logger(), "Real hardware mode: using system wall clock.");
    }

    imp_cmd_pub_ = this->create_publisher<corgi_msgs::msg::ImpedanceCmdStamped>(
        "impedance/command", 1000);
    trigger_sub_ = this->create_subscription<corgi_msgs::msg::TriggerStamped>(
        "trigger", 1000,
        std::bind(&GslipPronkNode::trigger_cb, this, std::placeholders::_1));
    motor_state_sub_ = this->create_subscription<corgi_msgs::msg::MotorStateStamped>(
        "motor/state", 1000,
        std::bind(&GslipPronkNode::motor_state_cb, this, std::placeholders::_1));
    imu_sub_ = this->create_subscription<corgi_msgs::msg::ImuStamped>(
        "imu", 1000,
        std::bind(&GslipPronkNode::imu_cb, this, std::placeholders::_1));

    imp_cmd_modules_ = {
        &imp_cmd_.module_a,
        &imp_cmd_.module_b,
        &imp_cmd_.module_c,
        &imp_cmd_.module_d
    };

    if (!load_template(template_path)) {
        RCLCPP_FATAL(this->get_logger(),
                     "Could not load the stride template from '%s'. Generate it with "
                     "LegWheel: uv run python examples/gslip/export_pronk_csv.py",
                     template_path.c_str());
        throw std::runtime_error("missing stride template");
    }

    RCLCPP_INFO(this->get_logger(),
                "Loaded %zu template rows (%.4f s stride), k_radial=%.0f N/m per leg",
                template_.size(), template_.back().t, k_radial_);
}

void GslipPronkNode::trigger_cb(const corgi_msgs::msg::TriggerStamped::SharedPtr msg) {
    trigger_ = msg->enable;
}

void GslipPronkNode::motor_state_cb(const corgi_msgs::msg::MotorStateStamped::SharedPtr msg) {
    motor_state_ = *msg;
}

void GslipPronkNode::imu_cb(const corgi_msgs::msg::ImuStamped::SharedPtr msg) {
    imu_ = *msg;
}

bool GslipPronkNode::load_template(const std::string& path) {
    std::ifstream file(path);
    if (!file.is_open()) return false;

    std::string line;
    if (!std::getline(file, line)) return false;  // header

    template_.clear();
    while (std::getline(file, line)) {
        if (line.empty()) continue;
        std::stringstream ss(line);
        std::string cell;
        TemplateRow row{};
        std::vector<double> values;
        while (std::getline(ss, cell, ',')) {
            values.push_back(std::stod(cell));
        }
        if (values.size() < 5) return false;
        row.t = values[0];
        row.theta = values[1];
        row.beta = values[2];
        row.gamma = values[3];
        row.in_stance = values[4] > 0.5;
        template_.push_back(row);
    }
    // The final row is the wrap-around of the first; dropping it keeps the
    // cycle from stalling for one tick at every stride boundary.
    if (template_.size() > 1) template_.pop_back();
    return template_.size() > 1;
}

void GslipPronkNode::apply_row(const TemplateRow& row) {
    for (auto* cmd : imp_cmd_modules_) {
        cmd->theta = row.theta;
        cmd->beta = row.beta;
        cmd->gamma = row.gamma;

        // No force feedback yet: with fx/fy/fz and the inertia terms at zero,
        // force_control degenerates to a pure (K, B) impedance and needs no
        // contact-force estimate.
        cmd->fx = 0.0; cmd->fy = 0.0; cmd->fz = 0.0;
        cmd->mx = 0.0; cmd->my = 0.0; cmd->mz = 0.0;

        if (row.in_stance) {
            cmd->leg_frame = true;
            cmd->kx = k_radial_;      // along the leg: the virtual spring
            cmd->ky = k_lateral_;
            cmd->kz = k_tangential_;  // perpendicular, in the sagittal plane
            cmd->bx = b_radial_;
            cmd->by = b_lateral_;
            cmd->bz = b_tangential_;
        } else {
            cmd->leg_frame = false;
            cmd->kx = k_flight_;
            cmd->ky = k_flight_;
            cmd->kz = k_flight_;
            cmd->bx = b_flight_;
            cmd->by = b_flight_;
            cmd->bz = b_flight_;
        }
    }
    // Legs A and D are on one side, B and C on the other; beta is mirrored
    // between sides in the same way exp_sim_stay does it.
    imp_cmd_modules_[1]->beta = -row.beta;
    imp_cmd_modules_[2]->beta = -row.beta;
}

void GslipPronkNode::execute_standup_phase() {
    // Ramp from wherever the robot actually is, not from a hardcoded folded
    // pose. If a CSV has already stood the robot up (theta ~ 120 deg),
    // starting the ramp at 17 deg commands an immediate collapse.
    //
    // A single spin_some() is NOT enough: the subscription has not yet
    // discovered the publisher at construction time, so motor_state_ is still
    // zero-initialised and the fallback fires even though the robot is
    // standing. Wait for a real sample. Wall-clock sleep, deliberately -- this
    // must work before the sim clock is known to be running.
    const int kMaxWaitMs = 5000;
    int waited_ms = 0;
    while (rclcpp::ok() && motor_state_.module_a.theta == 0.0 && waited_ms < kMaxWaitMs) {
        rclcpp::spin_some(this->get_node_base_interface());
        std::this_thread::sleep_for(std::chrono::milliseconds(10));
        waited_ms += 10;
    }

    double theta_start = motor_state_.module_a.theta;
    double beta_start = motor_state_.module_a.beta;
    if (theta_start == 0.0) {
        theta_start = 17.0 / 180.0 * M_PI;
        beta_start = 0.0;
        RCLCPP_ERROR(this->get_logger(),
                     "No motor/state after %d ms. Assuming the folded pose, which will "
                     "COLLAPSE a standing robot. Check that the simulator is running.",
                     kMaxWaitMs);
    } else {
        RCLCPP_INFO(this->get_logger(), "Got motor/state after %d ms", waited_ms);
    }

    const TemplateRow& first = template_.front();
    RCLCPP_INFO(this->get_logger(),
                "Ramping from measured theta=%.1f deg to template theta=%.1f deg",
                theta_start * 180.0 / M_PI, first.theta * 180.0 / M_PI);

    rclcpp::Duration period(0, 1000000);  // 1 ms
    rclcpp::Time next_time = this->now();

    for (int i = 0; i < standup_ticks_ && rclcpp::ok(); i++) {
        rclcpp::spin_some(this->get_node_base_interface());

        const double s = static_cast<double>(i) / standup_ticks_;
        TemplateRow row{};
        row.t = 0.0;
        row.theta = theta_start + s * (first.theta - theta_start);
        row.beta = beta_start + s * (first.beta - beta_start);
        row.gamma = 0.0;
        row.in_stance = false;  // soft gains while posing
        apply_row(row);

        imp_cmd_.header.stamp = this->now();
        imp_cmd_pub_->publish(imp_cmd_);

        next_time = next_time + period;
        rclcpp::sleep_for(std::chrono::nanoseconds(
            std::max<int64_t>(0, (next_time - this->now()).nanoseconds())));
    }
}

void GslipPronkNode::execute_running_phase() {
    rclcpp::Duration period(0, 1000000);  // 1 ms
    rclcpp::Time next_time = this->now();

    // Let the robot settle onto its legs before striding. In experiment mode
    // the trigger that got us here also removed the support box.
    if (settle_ticks_ > 0) {
        RCLCPP_INFO(this->get_logger(), "Settling for %d ms before the first stride",
                    settle_ticks_);
        TemplateRow settle = template_.front();
        settle.in_stance = true;
        for (int i = 0; i < settle_ticks_ && rclcpp::ok() && trigger_; i++) {
            rclcpp::spin_some(this->get_node_base_interface());
            apply_row(settle);
            imp_cmd_.header.stamp = this->now();
            imp_cmd_pub_->publish(imp_cmd_);
            next_time = next_time + period;
            rclcpp::sleep_for(std::chrono::nanoseconds(
                std::max<int64_t>(0, (next_time - this->now()).nanoseconds())));
        }
    }

    RCLCPP_INFO(this->get_logger(), "Running the G-SLIP pronk template");
    size_t index = 0;
    size_t stride_count = 0;

    while (rclcpp::ok() && trigger_) {
        rclcpp::spin_some(this->get_node_base_interface());

        apply_row(template_[index]);
        imp_cmd_.header.stamp = this->now();
        imp_cmd_pub_->publish(imp_cmd_);

        index++;
        if (index >= template_.size()) {
            index = 0;
            stride_count++;
            if (stride_count % 10 == 0) {
                RCLCPP_INFO(this->get_logger(), "%zu strides", stride_count);
            }
        }

        next_time = next_time + period;
        rclcpp::sleep_for(std::chrono::nanoseconds(
            std::max<int64_t>(0, (next_time - this->now()).nanoseconds())));
    }

    RCLCPP_INFO(this->get_logger(), "Stopped after %zu strides", stride_count);
}

void GslipPronkNode::run() {
    execute_standup_phase();

    rclcpp::Duration period(0, 1000000);  // 1 ms
    rclcpp::Time next_time = this->now();

    RCLCPP_INFO(this->get_logger(), "Holding pose; waiting for trigger");
    while (rclcpp::ok()) {
        rclcpp::spin_some(this->get_node_base_interface());

        if (trigger_) {
            execute_running_phase();
        } else {
            TemplateRow hold = template_.front();
            hold.in_stance = hold_stance_;
            apply_row(hold);
            imp_cmd_.header.stamp = this->now();
            imp_cmd_pub_->publish(imp_cmd_);
        }

        next_time = next_time + period;
        rclcpp::sleep_for(std::chrono::nanoseconds(
            std::max<int64_t>(0, (next_time - this->now()).nanoseconds())));
    }
}

int main(int argc, char** argv) {
    rclcpp::init(argc, argv);
    auto node = std::make_shared<GslipPronkNode>();
    node->run();
    rclcpp::shutdown();
    return 0;
}
